shortcuts:
  gc: commit.yaml
  tno: test-no_options.yaml
  tof: test-on_failure.yaml
  t: test.yaml
  tf: test-fail.yaml
  ts: test-secret.yaml
  tp: test-params.yaml
  tc: test-capture.yaml
  tcc: test-concurrentcy.yaml
