shortcuts:
  tf: test-fail.yaml
  tp: test-params.yaml
  gc: commit.yaml
  tfp: test-fallback-proceed-on-failure.yaml
  tfb: test-fallback.yaml
  t: test.yaml
  tno: test-no_options.yaml
  tcc: test-concurrentcy.yaml
  tc: test-capture.yaml
  tof: test-on_failure.yaml
  ts: test-secret.yaml
