//! `zirv context <verb>` -- a top-level command family (issue #45, "Context
//! 7/8"), sibling to `zirv ctx` rather than one of its verbs: intercepted
//! against raw argv in `main.rs` exactly like `ctx`/`chat`/`agent` (see
//! `is_top_level_context` there), because this is not an alias for anything
//! under `zirv ctx` -- it is its own command family, with `sync` as its
//! first verb.
//!
//! **Goal.** `.zirv/context/` (`context.rs`) is the canonical source of
//! project instructions for every Zirv-launched harness (`compile.rs` reads
//! it at every launch). Claude and Codex can also be launched *directly*,
//! outside zirv entirely, in which case only their own native files --
//! `CLAUDE.md`, `AGENTS.md` -- are ever read. `sync` is the explicit,
//! opt-in bridge between the two: it never runs on its own (no autogeneration
//! at launch, no side effect from `compile::compile`), and every mode it
//! offers is a deliberate, separately-named choice -- never an implicit
//! side effect of another one.
//!
//! **Three modes, mutually exclusive** (`SyncArgs`'s `mode` `ArgGroup`):
//! - default / `--report`: inspect and report differences. Never writes.
//! - `--import`: native `CLAUDE.md`/`AGENTS.md` -> canonical
//!   `.zirv/context/{claude,codex}.md`.
//! - `--generate`: canonical `.zirv/context/*.md` -> managed `CLAUDE.md`/
//!   `AGENTS.md`.
//!
//! **The central safety property.** `--generate` must never silently
//! overwrite a hand-maintained native file. Every generated file's first
//! line is [`MANAGED_MARKER`], a stable, deterministic, machine-readable
//! header; `--generate` refuses to touch any existing native file whose
//! content does not start with it (`is_managed`), and reports the refusal
//! plainly rather than failing loudly or overwriting anyway. Only an
//! explicit `--force` -- the user's own deliberate choice, never a default
//! -- lifts that refusal, for both `--generate` (replace an unmanaged
//! native file) and `--import` (replace canonical content that already
//! differs from the native file being imported).
//!
//! **Determinism and idempotency.** [`render_generated`] is a pure function
//! of its two inputs (no clock, no environment read, the same discipline
//! `compile.rs`/`rot.rs` hold themselves to): the same canonical content
//! always renders to byte-identical output, and generating twice in a row
//! with nothing changed is a true no-op (`generate_one` compares against
//! the file already on disk before writing anything).
//!
//! **Content routing.** [`render_generated`] takes the canonical common text
//! and exactly one harness-specific text; the two call sites in
//! `run_generate` pass `claude.md`'s content only into the `CLAUDE.md`
//! render and `codex.md`'s content only into the `AGENTS.md` render, so
//! there is no code path through which one harness's canonical addition
//! could reach the other's generated file.
//!
//! **Instructions only, never enforcement.** A generated file is prose,
//! nothing else: [`render_generated`] never touches `policy::EffectivePolicy`
//! or any `Support` state, and carries no permission/sandbox/security claim,
//! because outside zirv there is no zirv process to enforce one -- the same
//! "advisory, not enforcement" line `policy.rs`'s own module doc draws for
//! Markdown instructions in general.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use clap::{Parser, Subcommand};

use super::CtxResult;
use super::context_status::{self, StatusArgs};
use super::{context, drift, optimize};

/// A generated compatibility file's first line: stable across every
/// regeneration (no timestamp, no session-specific detail -- either would
/// break byte-for-byte determinism), and distinctive enough that a native
/// `CLAUDE.md`/`AGENTS.md` a human wrote by hand would essentially never
/// start with it by coincidence. `MANAGED_MARKER_PREFIX` is what `is_managed`
/// actually checks against: a prefix rather than an exact-string match, so a
/// future revision of the trailing wording never breaks recognition of files
/// generated by an older zirv binary.
pub const MANAGED_MARKER_PREFIX: &str = "<!-- zirv:managed-context-file";
pub const MANAGED_MARKER: &str = "<!-- zirv:managed-context-file -- generated by \
`zirv context sync --generate` from .zirv/context/. Edit the files there, not this one: \
regenerating overwrites it, and a hand edit here is never picked up by anything zirv does. -->";

/// Whether `text` is a file zirv itself generated, checked the same way a
/// human would recognise it: does it visibly start with the marker. Leading
/// blank lines are tolerated (a human re-saving the file with an editor that
/// adds one is still a zirv-managed file), but the marker must be the first
/// non-blank line -- a native file that merely *mentions* the marker text
/// somewhere in its body (quoting this very module's docs, say) must not be
/// misread as managed.
pub fn is_managed(text: &str) -> bool {
    text.trim_start().starts_with(MANAGED_MARKER_PREFIX)
}

/// Narrows `surfaces` for `drift::analyze`'s duplicate/precedence-level
/// comparison (issue #105): drops any surface that is itself a zirv-managed
/// native file (`is_managed` on its text). A managed `CLAUDE.md`/`AGENTS.md`
/// is a verbatim render of `.zirv/context/` (`context_cli::run_generate`),
/// so pairing it against the canonical layer it was rendered from in a
/// `duplicate-canonicalizable`/`precedence-shadowing` finding is a
/// tautology, not real drift -- right after `zirv context sync --generate
/// --force`, `zirv context status`/`context sync --report` were reporting
/// exactly that. Reuses `is_managed`, the one marker parser in this
/// codebase, rather than a second one; both call sites (`context_status::
/// run_with`, this module's own `run_report`) still pass the UNFILTERED
/// `surfaces` to their own surfaces listing, so sizes/budgets are unaffected
/// -- only what `drift::analyze` gets to compare narrows.
pub fn surfaces_for_drift(surfaces: &[optimize::Surface]) -> Vec<optimize::Surface> {
    surfaces
        .iter()
        .filter(|surface| !is_managed(&surface.text))
        .cloned()
        .collect()
}

/// `<repo>/CLAUDE.md` -- Claude's own native instruction file, read by Claude
/// Code directly regardless of whether zirv is involved at all. Same fixed
/// path `optimize::collect_surfaces` reads for `Layer::RepoClaudeMd`; not
/// reused directly from there because this module needs the bare path, not a
/// `Surface`.
fn native_claude_path(repo: &Path) -> PathBuf {
    repo.join("CLAUDE.md")
}

/// `<repo>/AGENTS.md` -- Codex's own native instruction file. Same fixed path
/// `optimize::collect_surfaces` reads for `Layer::RepoAgentsMd`.
fn native_codex_path(repo: &Path) -> PathBuf {
    repo.join("AGENTS.md")
}

/// The prefix of a generated file's canonical-content provenance line. Sits
/// on the line immediately after [`MANAGED_MARKER`], so it is inside the
/// managed prefix [`is_managed`] recognises and a zirv old enough not to know
/// about it still reads the file as managed.
pub const CANONICAL_HASH_PREFIX: &str = "<!-- zirv:canonical-sha256:";

/// SHA-256 over the exact canonical inputs a render used, as 64 lowercase
/// hex characters.
///
/// Domain-separated by length prefix, not by a delimiter: hashing
/// `common + harness` directly would give `("ab","c")` and `("a","bc")` the
/// same digest, and a collision here would make `compile.rs` skip injecting
/// content the native file does not actually hold -- a silent instruction
/// loss, which is the one failure this whole phase must not introduce.
///
/// Hashes the TRIMMED text, matching what [`render_generated`] actually
/// writes, so trailing-whitespace churn in `.zirv/context/` cannot
/// invalidate a file whose delivered bytes are unchanged. An absent or
/// all-whitespace input is `None`/empty for both, so the two agree.
pub fn canonical_sha256(common: Option<&str>, harness_specific: Option<&str>) -> String {
    use sha2::{Digest, Sha256};
    let normalize = |t: Option<&str>| -> String {
        t.map(str::trim)
            .filter(|s| !s.is_empty())
            .unwrap_or("")
            .to_string()
    };
    let common = normalize(common);
    let harness = normalize(harness_specific);
    let mut hasher = Sha256::new();
    hasher.update(b"zirv-canonical-v1");
    for part in [&common, &harness] {
        hasher.update((part.len() as u64).to_le_bytes());
        hasher.update(part.as_bytes());
    }
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

/// The hash a generated file states it was rendered from, if it states one.
/// `None` for a file generated before this change, for a native file, or for
/// a malformed line -- every one of which correctly means "cannot prove
/// equality", which `compile.rs` reads as "inject as before".
///
/// Issue #155, Task 3.1 produces this reader; only its own tests call it
/// until Task 3.2 wires `compile.rs`'s injection-skip to it, so
/// `#[allow(dead_code)]` documents the gap as deliberate rather than an
/// oversight, the same way `announce.rs`'s macOS-only variant is marked.
#[allow(dead_code)]
pub fn embedded_canonical_sha256(text: &str) -> Option<String> {
    let line = text
        .lines()
        .take(4)
        .find_map(|line| line.trim().strip_prefix(CANONICAL_HASH_PREFIX))?;
    let hex = line.trim().strip_suffix("-->")?.trim();
    (hex.len() == 64
        && hex
            .chars()
            .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()))
    .then(|| hex.to_string())
}

/// Renders one generated compatibility file: the managed marker, then the
/// canonical-content provenance hash, then the canonical common text (if any
/// and non-blank), then the harness-specific canonical text (if any and
/// non-blank). A pure function of its two arguments -- no clock, no
/// environment, no filesystem read of its own -- so two calls with the same
/// inputs always produce the same bytes, and the only way two harnesses'
/// generated files could ever share content is if the caller passed the same
/// `harness_specific` text to both, which `run_generate` never does (see
/// this module's own doc).
fn render_generated(common: Option<&str>, harness_specific: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(MANAGED_MARKER);
    out.push('\n');

    out.push_str(CANONICAL_HASH_PREFIX);
    out.push_str(&canonical_sha256(common, harness_specific));
    out.push_str(" -->\n");

    let common = common.map(str::trim).filter(|s| !s.is_empty());
    let harness = harness_specific.map(str::trim).filter(|s| !s.is_empty());

    if let Some(common) = common {
        out.push('\n');
        out.push_str(common);
        out.push('\n');
    }
    if let Some(harness) = harness {
        out.push('\n');
        out.push_str(harness);
        out.push('\n');
    }
    out
}

/// What `generate_one` actually did to one native file.
#[derive(Debug, Clone, PartialEq, Eq)]
enum GenerateOutcome {
    /// The file existed, was not a managed file, and `force` was not given:
    /// nothing was written. The central safety property this module exists
    /// for.
    Refused,
    /// The file existed, was managed (or `force` was given), and already
    /// held exactly `content`: nothing was written, but not because of a
    /// refusal -- there was simply nothing to change. Proves generation is
    /// idempotent, not merely non-destructive.
    Unchanged,
    /// `content` was written. `created` distinguishes a brand-new file from
    /// a regenerated one, for the report line only -- both are equally safe.
    Written { created: bool },
}

/// Writes `content` to `path` if it is safe to: the file is absent, already
/// managed, already holds `content` verbatim, or the caller passed `force`.
/// Refuses (see `GenerateOutcome::Refused`) only when the file exists, is
/// not managed, and `force` is false -- the one case where writing would
/// silently destroy hand-maintained content.
fn generate_one(path: &Path, content: &str, force: bool) -> std::io::Result<GenerateOutcome> {
    match fs::read_to_string(path) {
        Ok(existing) => {
            if existing == content {
                return Ok(GenerateOutcome::Unchanged);
            }
            if !is_managed(&existing) && !force {
                return Ok(GenerateOutcome::Refused);
            }
            fs::write(path, content)?;
            Ok(GenerateOutcome::Written { created: false })
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, content)?;
            Ok(GenerateOutcome::Written { created: true })
        }
        Err(e) => Err(e),
    }
}

/// What `import_one` actually did with one native file.
#[derive(Debug, Clone, PartialEq, Eq)]
enum ImportOutcome {
    /// No native file to import from; nothing to do, not an error.
    NoNativeFile,
    /// The "native" file is itself a zirv-generated file (round-tripping a
    /// `--generate` output straight back into `--import` would just restate
    /// the canonical content it came from) -- refused so a user does not
    /// silently import zirv's own output as if it were something new.
    RefusedManaged,
    /// The canonical target already exists with different content and
    /// `force` was not given: importing would silently discard whatever is
    /// there now.
    RefusedExistingCanonical,
    /// The canonical target already held exactly the native text (trimmed);
    /// nothing written.
    Unchanged,
    /// The native text was written to the canonical target.
    Imported,
}

/// Copies `native_path`'s content into `canonical_path` verbatim (trimmed of
/// surrounding whitespace), refusing to overwrite existing, differing
/// canonical content unless `force` is given. Never invents structure the
/// native file doesn't have -- splitting common from harness-specific
/// content is `--report`'s drift-analysis job to surface, and a human's job
/// to act on, not something this function guesses at.
fn import_one(
    native_path: &Path,
    canonical_path: &Path,
    force: bool,
) -> std::io::Result<ImportOutcome> {
    let native_text = match fs::read_to_string(native_path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok(ImportOutcome::NoNativeFile);
        }
        Err(e) => return Err(e),
    };
    if is_managed(&native_text) {
        return Ok(ImportOutcome::RefusedManaged);
    }
    let native_trimmed = native_text.trim();

    if let Ok(existing) = fs::read_to_string(canonical_path) {
        if existing.trim() == native_trimmed {
            return Ok(ImportOutcome::Unchanged);
        }
        if !force {
            return Ok(ImportOutcome::RefusedExistingCanonical);
        }
    }

    if let Some(parent) = canonical_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(canonical_path, format!("{native_trimmed}\n"))?;
    Ok(ImportOutcome::Imported)
}

/// The repo-root surface cap `--report` reads canonical/native files under.
/// Deliberately a fixed local constant rather than `CtxConfig::optimize.
/// max_surface_bytes`: `sync --report` is read-only and self-contained by
/// design (issue #45's opt-in migration requirement), and pulling in a full
/// `CtxConfig::load` here would make a report's own drift section depend on
/// a config load that has nothing to do with what this verb reports on.
/// Matches `OptimizeConfig::default().max_surface_bytes` so a very large
/// hand-authored file is capped the same way `zirv ctx optimize` already
/// caps it, not silently truncated to something smaller.
const REPORT_MAX_SURFACE_BYTES: usize = 200_000;

fn run_report<W: Write>(w: &mut W, repo: &Path) -> CtxResult<i32> {
    writeln!(
        w,
        "zirv context sync --report (read-only; nothing on disk is changed)\n"
    )?;

    writeln!(w, "canonical context (.zirv/context/):")?;
    for (label, path) in [
        ("common.md", context::common_path(repo)),
        ("claude.md", context::claude_path(repo)),
        ("codex.md", context::codex_path(repo)),
    ] {
        let status = if path.exists() { "present" } else { "missing" };
        writeln!(w, "  {label}: {status} ({})", path.display())?;
    }

    writeln!(w, "\nnative compatibility files:")?;
    for (label, path) in [
        ("CLAUDE.md", native_claude_path(repo)),
        ("AGENTS.md", native_codex_path(repo)),
    ] {
        let status = match fs::read_to_string(&path) {
            Ok(text) if is_managed(&text) => "present, zirv-managed".to_string(),
            Ok(_) => "present, hand-maintained (not zirv-managed)".to_string(),
            Err(_) => "missing".to_string(),
        };
        writeln!(w, "  {label}: {status} ({})", path.display())?;
    }

    let home = crate::utils::home_dir().ok();
    let surfaces = optimize::collect_surfaces(home.as_deref(), repo, REPORT_MAX_SURFACE_BYTES);
    let findings = drift::analyze(&surfaces_for_drift(&surfaces));
    if findings.is_empty() {
        writeln!(
            w,
            "\nno differences detected between canonical context and native files"
        )?;
    } else {
        writeln!(w, "\n{} finding(s):", findings.len())?;
        for finding in &findings {
            writeln!(w, "  [{}] {}", finding.severity.as_str(), finding.title)?;
            for evidence in &finding.evidence {
                writeln!(w, "      {evidence}")?;
            }
        }
    }

    writeln!(
        w,
        "\nRun `zirv context sync --import` to bring native file content into canonical \
         context, or `zirv context sync --generate` to render canonical context into managed \
         native files."
    )?;
    Ok(0)
}

fn run_generate<W: Write>(w: &mut W, repo: &Path, force: bool) -> CtxResult<i32> {
    writeln!(w, "zirv context sync --generate")?;

    let common = fs::read_to_string(context::common_path(repo)).ok();
    let mut any_refused = false;

    for (label, canonical_path, native_path) in [
        (
            "claude",
            context::claude_path(repo),
            native_claude_path(repo),
        ),
        ("codex", context::codex_path(repo), native_codex_path(repo)),
    ] {
        let harness = fs::read_to_string(&canonical_path).ok();
        let has_common = common.as_deref().is_some_and(|t| !t.trim().is_empty());
        let has_harness = harness.as_deref().is_some_and(|t| !t.trim().is_empty());
        if !has_common && !has_harness {
            writeln!(w, "  {label}: no canonical content, nothing to generate")?;
            continue;
        }

        let content = render_generated(common.as_deref(), harness.as_deref());
        match generate_one(&native_path, &content, force)? {
            GenerateOutcome::Refused => {
                any_refused = true;
                writeln!(
                    w,
                    "  {label}: refused -- {} exists and is not a zirv-managed file. Run \
                     `zirv context sync --import` to bring its content into canonical context \
                     first, or re-run `--generate --force` to replace it.",
                    native_path.display()
                )?;
            }
            GenerateOutcome::Unchanged => {
                writeln!(w, "  {label}: unchanged ({})", native_path.display())?;
            }
            GenerateOutcome::Written { created: true } => {
                writeln!(w, "  {label}: created {}", native_path.display())?;
            }
            GenerateOutcome::Written { created: false } => {
                writeln!(w, "  {label}: regenerated {}", native_path.display())?;
            }
        }
    }

    Ok(if any_refused { 1 } else { 0 })
}

fn run_import<W: Write>(w: &mut W, repo: &Path, force: bool) -> CtxResult<i32> {
    writeln!(w, "zirv context sync --import")?;

    let mut any_refused = false;
    for (label, native_path, canonical_path) in [
        (
            "claude",
            native_claude_path(repo),
            context::claude_path(repo),
        ),
        ("codex", native_codex_path(repo), context::codex_path(repo)),
    ] {
        match import_one(&native_path, &canonical_path, force)? {
            ImportOutcome::NoNativeFile => {
                writeln!(
                    w,
                    "  {label}: no {} found, nothing to import",
                    native_path.display()
                )?;
            }
            ImportOutcome::RefusedManaged => {
                any_refused = true;
                writeln!(
                    w,
                    "  {label}: refused -- {} is itself a zirv-generated file; there is \
                     nothing new to import from it",
                    native_path.display()
                )?;
            }
            ImportOutcome::RefusedExistingCanonical => {
                any_refused = true;
                writeln!(
                    w,
                    "  {label}: refused -- {} already has different content; re-run \
                     `--import --force` to replace it",
                    canonical_path.display()
                )?;
            }
            ImportOutcome::Unchanged => {
                writeln!(w, "  {label}: unchanged ({})", canonical_path.display())?;
            }
            ImportOutcome::Imported => {
                writeln!(w, "  {label}: imported into {}", canonical_path.display())?;
            }
        }
    }

    Ok(if any_refused { 1 } else { 0 })
}

#[derive(Debug, clap::Args)]
#[command(group(clap::ArgGroup::new("sync_mode").args(["report", "import", "generate"]).multiple(false)))]
pub struct SyncArgs {
    /// Report differences between canonical context and native files. The
    /// default when no mode flag is given. Never writes anything.
    #[arg(long)]
    pub report: bool,
    /// Import native CLAUDE.md/AGENTS.md content into canonical
    /// `.zirv/context/{claude,codex}.md`.
    #[arg(long)]
    pub import: bool,
    /// Generate managed CLAUDE.md/AGENTS.md from canonical
    /// `.zirv/context/` content.
    #[arg(long)]
    pub generate: bool,
    /// Explicitly overwrite: with `--import`, replace canonical content that
    /// already differs; with `--generate`, replace a native file that is not
    /// zirv-managed. Has no effect with the default report mode.
    #[arg(long)]
    pub force: bool,
}

enum SyncMode {
    Report,
    Import,
    Generate,
}

fn mode(args: &SyncArgs) -> SyncMode {
    if args.import {
        SyncMode::Import
    } else if args.generate {
        SyncMode::Generate
    } else {
        SyncMode::Report
    }
}

pub fn run_with<W: Write>(args: &SyncArgs, w: &mut W, repo: &Path) -> CtxResult<i32> {
    match mode(args) {
        SyncMode::Report => run_report(w, repo),
        SyncMode::Import => run_import(w, repo, args.force),
        SyncMode::Generate => run_generate(w, repo, args.force),
    }
}

pub fn run<W: Write>(args: &SyncArgs, w: &mut W) -> CtxResult<i32> {
    let repo = std::env::current_dir()?;
    run_with(args, w, &repo)
}

#[derive(Debug, Parser)]
#[command(
    name = "zirv context",
    about = "Compatibility workflow keeping .zirv/context/ canonical while CLAUDE.md/AGENTS.md stay usable outside zirv.",
    disable_help_subcommand = true
)]
pub struct ContextCli {
    #[command(subcommand)]
    pub verb: ContextVerb,
}

#[derive(Debug, Subcommand)]
pub enum ContextVerb {
    /// Inspect, import, or generate CLAUDE.md/AGENTS.md compatibility with
    /// canonical `.zirv/context/`.
    Sync(SyncArgs),
    /// Report exactly what Zirv-managed context a session would receive:
    /// discovered instruction surfaces, canonical vs native/harness-specific
    /// split, memory/mail/handoff contribution, the harness/orchestration
    /// roster, per-harness policy alignment, every configured budget, and
    /// duplicate/conflict counts -- all without starting a session (issue
    /// #46, "Context 8/8"). See `context_status.rs`.
    Status(StatusArgs),
}

/// `args[0]` is the literal "context" as it appeared in argv, mirroring
/// `ctx::dispatch`'s own convention.
pub fn dispatch(args: &[String]) -> i32 {
    let argv = std::iter::once("zirv context".to_string()).chain(args.iter().skip(1).cloned());
    let cli = match ContextCli::try_parse_from(argv) {
        Ok(cli) => cli,
        Err(err) => {
            let _ = err.print();
            // Same "help/version are informational, not a rejected
            // invocation" carve-out `ctx::dispatch` makes.
            if matches!(
                err.kind(),
                clap::error::ErrorKind::DisplayHelp | clap::error::ErrorKind::DisplayVersion
            ) {
                return 0;
            }
            return 2;
        }
    };

    let mut out = std::io::stdout();
    let result = match &cli.verb {
        ContextVerb::Sync(a) => run(a, &mut out),
        ContextVerb::Status(a) => context_status::run(a, &mut out),
    };

    match result {
        Ok(code) => code,
        Err(e) => {
            crate::output::error(e);
            1
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// T8 hermeticity: `run_with` resolves the developer's own global
    /// `~/CLAUDE.md`/context via `crate::utils::home_dir()` (see its call
    /// site around line 301), which is real-`$HOME`-backed and not otherwise
    /// injectable here (`run_with` takes no env lookup at all). Without a
    /// `HomeGuard`, every test in this module read whatever the real
    /// developer happens to have in their own home directory -- on a machine
    /// with a real `~/CLAUDE.md`, that showed up as spurious "findings"
    /// nothing in the test ever wrote, and false drift/no-drift results.
    /// Bundled into `repo()` itself (rather than added test-by-test) since
    /// every one of this module's tests goes through it and none of them
    /// want the real home. `home` is a subdirectory of the same tempdir
    /// (the handover.rs pattern) rather than a second `TempDir` -- neither
    /// `HomeGuard::set` nor anything it points `$HOME` at requires the
    /// directory to actually exist. Both the tempdir and the guard must
    /// still be bound to live names at the call site (every current caller
    /// uses `let (dir, _guard) = repo();`) -- dropping the guard restores
    /// the real `$HOME`, and dropping the tempdir deletes the tree `$HOME`
    /// now points into, reintroducing exactly the leak this helper exists
    /// to close.
    fn repo() -> (tempfile::TempDir, crate::commands::ctx::testenv::HomeGuard) {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::create_dir_all(dir.path().join(".zirv/context")).expect("mkdir");
        let home = dir.path().join("home");
        let guard = crate::commands::ctx::testenv::HomeGuard::set(&home);
        (dir, guard)
    }

    fn write_canonical(repo: &Path, name: &str, text: &str) {
        fs::write(repo.join(".zirv/context").join(name), text).expect("write canonical");
    }

    fn run_sync(args: &SyncArgs, repo: &Path) -> (i32, String) {
        let mut out = Vec::new();
        let code = run_with(args, &mut out, repo).expect("run_with");
        (code, String::from_utf8(out).expect("utf8"))
    }

    fn report_args() -> SyncArgs {
        SyncArgs {
            report: true,
            import: false,
            generate: false,
            force: false,
        }
    }
    fn import_args(force: bool) -> SyncArgs {
        SyncArgs {
            report: false,
            import: true,
            generate: false,
            force,
        }
    }
    fn generate_args(force: bool) -> SyncArgs {
        SyncArgs {
            report: false,
            import: false,
            generate: true,
            force,
        }
    }

    // -- render_generated: determinism, idempotency, content routing, no
    // policy claims --------------------------------------------------------

    #[test]
    fn render_generated_is_deterministic() {
        let first = render_generated(Some("Run tests."), Some("Claude-only note."));
        let second = render_generated(Some("Run tests."), Some("Claude-only note."));
        assert_eq!(first, second);
    }

    #[test]
    fn render_generated_starts_with_the_managed_marker() {
        let text = render_generated(Some("hi"), None);
        assert!(text.starts_with(MANAGED_MARKER));
        assert!(is_managed(&text));
    }

    #[test]
    fn render_generated_with_no_canonical_content_is_just_the_marker_and_hash() {
        let text = render_generated(None, None);
        assert_eq!(
            text,
            format!(
                "{MANAGED_MARKER}\n{CANONICAL_HASH_PREFIX}{} -->\n",
                canonical_sha256(None, None)
            )
        );
    }

    #[test]
    fn render_generated_never_contains_policy_or_permission_claims() {
        let text = render_generated(
            Some("Always run the full test suite before committing."),
            Some("Prefer the native tool-use loop over shell escapes."),
        );
        let lower = text.to_lowercase();
        for banned in [
            "permission",
            "sandbox",
            "enforce",
            "enforced",
            "policy",
            "unsupported",
            "operatorcontrolled",
            "degraded",
            "zirv policy",
        ] {
            assert!(
                !lower.contains(banned),
                "generated output must never claim policy/permission/enforcement: found \
                 '{banned}' in {text:?}"
            );
        }
    }

    #[test]
    fn common_content_reaches_both_generated_files() {
        let common = "Always run the full test suite before committing.";
        let claude_out = render_generated(Some(common), Some("Claude-only addition."));
        let codex_out = render_generated(Some(common), Some("Codex-only addition."));
        assert!(claude_out.contains(common));
        assert!(codex_out.contains(common));
    }

    #[test]
    fn harness_specific_content_never_leaks_into_the_other_harness() {
        let claude_out = render_generated(None, Some("Claude-only: prefer the native tool loop."));
        let codex_out = render_generated(None, Some("Codex-only: prefer sandboxed exec."));

        assert!(claude_out.contains("Claude-only"));
        assert!(!claude_out.contains("Codex-only"));
        assert!(codex_out.contains("Codex-only"));
        assert!(!codex_out.contains("Claude-only"));
    }

    // -- canonical-content hash: provenance stamp for Task 3.2's dedupe -----

    /// Issue #155, Phase 3: a generated file states, in its own bytes, which
    /// canonical content it was rendered from. That is what lets `compile.rs`
    /// prove -- not guess -- that the harness has already read these exact
    /// instructions natively, and skip re-injecting them.
    #[test]
    fn a_generated_file_carries_the_hash_of_the_canonical_content_it_rendered() {
        let rendered = render_generated(Some("common text"), Some("claude text"));
        let embedded = embedded_canonical_sha256(&rendered).expect("a hash line");
        assert_eq!(
            embedded,
            canonical_sha256(Some("common text"), Some("claude text"))
        );
        assert_eq!(embedded.len(), 64);
        assert!(
            embedded
                .chars()
                .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase())
        );
        assert!(
            is_managed(&rendered),
            "the hash line must sit INSIDE the managed prefix, so an older binary still \
             recognises the file as managed"
        );
    }

    /// Domain separation: the two halves must not be concatenable into each
    /// other. Without a length-or-delimiter-committed hash, moving one
    /// character across the boundary would produce the same digest, and the
    /// dedupe would then skip injecting content the file does NOT hold.
    #[test]
    fn the_canonical_hash_cannot_be_collided_by_moving_the_boundary() {
        assert_ne!(
            canonical_sha256(Some("ab"), Some("c")),
            canonical_sha256(Some("a"), Some("bc"))
        );
        assert_ne!(
            canonical_sha256(Some("x"), None),
            canonical_sha256(None, Some("x"))
        );
    }

    /// The hash is computed over the same TRIMMED text `render_generated`
    /// actually writes, so trailing-whitespace churn in `.zirv/context/`
    /// never invalidates a file whose delivered bytes did not change.
    #[test]
    fn the_canonical_hash_ignores_whitespace_the_render_itself_trims() {
        assert_eq!(
            canonical_sha256(Some("common text"), None),
            canonical_sha256(Some("\n\n  common text  \n"), None)
        );
        assert_eq!(
            canonical_sha256(Some("common"), Some("   ")),
            canonical_sha256(Some("common"), None),
            "an all-whitespace harness file renders nothing, so it must hash as nothing"
        );
    }

    /// A file with no hash line at all -- one generated by an older zirv --
    /// reads as `None`, never as an error and never as a wrong hash.
    #[test]
    fn a_file_generated_before_this_change_has_no_embedded_hash() {
        let old = format!("{MANAGED_MARKER}\n\ncommon text\n");
        assert!(is_managed(&old));
        assert_eq!(embedded_canonical_sha256(&old), None);
    }

    /// Regeneration stays byte-for-byte deterministic: no clock, no session
    /// detail. `generate_one`'s `Unchanged` outcome depends on it.
    #[test]
    fn rendering_twice_with_the_same_inputs_produces_identical_bytes() {
        assert_eq!(
            render_generated(Some("common"), Some("harness")),
            render_generated(Some("common"), Some("harness"))
        );
    }

    // -- is_managed -----------------------------------------------------

    #[test]
    fn is_managed_recognises_the_marker_and_tolerates_leading_blank_lines() {
        assert!(is_managed(MANAGED_MARKER));
        assert!(is_managed(&format!("\n\n{MANAGED_MARKER}\nmore text")));
    }

    #[test]
    fn is_managed_rejects_hand_authored_content_even_if_it_mentions_the_marker_text() {
        assert!(!is_managed(
            "# My CLAUDE.md\n\nHand-written instructions.\n"
        ));
        assert!(!is_managed(&format!(
            "# Notes\n\nSee {MANAGED_MARKER_PREFIX} for zirv's own format.\n"
        )));
    }

    // -- --report changes nothing -----------------------------------------

    #[test]
    fn report_mode_changes_nothing_on_disk() {
        let (dir, _guard) = repo();
        write_canonical(dir.path(), "common.md", "Always run tests.");
        let claude_native = native_claude_path(dir.path());
        fs::write(&claude_native, "# Hand-maintained CLAUDE.md\n").expect("write");
        let before = fs::read_to_string(&claude_native).expect("read");
        let canonical_before = fs::read_to_string(context::common_path(dir.path())).expect("read");

        let (code, out) = run_sync(&report_args(), dir.path());

        assert_eq!(code, 0);
        assert!(out.contains("read-only"));
        assert_eq!(fs::read_to_string(&claude_native).expect("read"), before);
        assert_eq!(
            fs::read_to_string(context::common_path(dir.path())).expect("read"),
            canonical_before
        );
        assert!(
            !context::claude_path(dir.path()).exists(),
            "report must not create any canonical file either"
        );
    }

    /// Issue #105: `--report` (like `context status`) must not report a
    /// zirv-managed native `CLAUDE.md` -- a verbatim render of
    /// `.zirv/context/` -- as duplicating the canonical layer it was
    /// rendered from.
    #[test]
    fn report_mode_finds_no_drift_between_canonical_content_and_its_own_managed_render() {
        let (dir, _guard) = repo();
        write_canonical(
            dir.path(),
            "common.md",
            "- always run the full test suite\n",
        );
        fs::write(
            native_claude_path(dir.path()),
            format!("{MANAGED_MARKER}\n\n- always run the full test suite\n"),
        )
        .expect("write");

        let (code, out) = run_sync(&report_args(), dir.path());
        assert_eq!(code, 0);
        assert!(
            out.contains("no differences detected between canonical context and native files"),
            "a zirv-managed native file must not be diffed against its own canonical source: {out}"
        );
    }

    #[test]
    fn report_mode_is_also_the_default_with_no_flags() {
        let (dir, _guard) = repo();
        let (code, out) = run_sync(
            &SyncArgs {
                report: false,
                import: false,
                generate: false,
                force: false,
            },
            dir.path(),
        );
        assert_eq!(code, 0);
        assert!(out.contains("read-only"));
    }

    // -- unmanaged native file causes refusal, not overwrite ---------------

    #[test]
    fn generate_refuses_to_overwrite_an_unmanaged_native_file() {
        let (dir, _guard) = repo();
        write_canonical(dir.path(), "common.md", "Always run the full test suite.");
        let claude_native = native_claude_path(dir.path());
        let hand_written = "# My own CLAUDE.md\n\nDo not touch this.\n";
        fs::write(&claude_native, hand_written).expect("write");

        let (code, out) = run_sync(&generate_args(false), dir.path());

        assert_eq!(code, 1, "a refusal must be a non-zero exit: {out}");
        assert!(out.contains("refused"), "got {out}");
        assert_eq!(
            fs::read_to_string(&claude_native).expect("read"),
            hand_written,
            "an unmanaged native file must never be silently overwritten"
        );
    }

    #[test]
    fn generate_with_force_replaces_an_unmanaged_native_file() {
        let (dir, _guard) = repo();
        write_canonical(dir.path(), "common.md", "Always run the full test suite.");
        let claude_native = native_claude_path(dir.path());
        fs::write(&claude_native, "# hand-written\n").expect("write");

        let (code, _out) = run_sync(&generate_args(true), dir.path());

        assert_eq!(code, 0);
        let content = fs::read_to_string(&claude_native).expect("read");
        assert!(is_managed(&content));
        assert!(content.contains("Always run the full test suite."));
    }

    // -- import round-trips into canonical paths ----------------------------

    #[test]
    fn import_round_trips_native_files_into_canonical_paths() {
        let (dir, _guard) = repo();
        fs::write(
            native_claude_path(dir.path()),
            "# Claude notes\n\nPrefer rg over grep.\n",
        )
        .expect("write");
        fs::write(
            native_codex_path(dir.path()),
            "# Codex notes\n\nRun in sandboxed exec.\n",
        )
        .expect("write");

        let (code, out) = run_sync(&import_args(false), dir.path());
        assert_eq!(code, 0, "got {out}");

        let claude_canonical =
            fs::read_to_string(context::claude_path(dir.path())).expect("read claude.md");
        assert!(claude_canonical.contains("Prefer rg over grep."));
        let codex_canonical =
            fs::read_to_string(context::codex_path(dir.path())).expect("read codex.md");
        assert!(codex_canonical.contains("Run in sandboxed exec."));

        // Re-running import with the same native content is a no-op, not a
        // refusal (the canonical target already matches).
        let (code, out) = run_sync(&import_args(false), dir.path());
        assert_eq!(code, 0, "got {out}");
        assert!(out.contains("unchanged"));
    }

    #[test]
    fn import_refuses_to_overwrite_differing_canonical_content_without_force() {
        let (dir, _guard) = repo();
        write_canonical(dir.path(), "claude.md", "Existing canonical content.");
        fs::write(
            native_claude_path(dir.path()),
            "# Different native content\n",
        )
        .expect("write");

        let (code, out) = run_sync(&import_args(false), dir.path());
        assert_eq!(code, 1, "got {out}");
        assert!(out.contains("refused"));
        assert_eq!(
            fs::read_to_string(context::claude_path(dir.path())).expect("read"),
            "Existing canonical content."
        );
    }

    #[test]
    fn import_refuses_a_native_file_that_is_itself_zirv_managed() {
        let (dir, _guard) = repo();
        fs::write(native_claude_path(dir.path()), MANAGED_MARKER).expect("write");

        let (code, out) = run_sync(&import_args(false), dir.path());
        assert_eq!(code, 1, "got {out}");
        assert!(out.contains("refused"));
        assert!(
            !context::claude_path(dir.path()).exists(),
            "importing zirv's own generated output must not create canonical content from it"
        );
    }

    #[test]
    fn import_with_no_native_files_is_a_clean_no_op() {
        let (dir, _guard) = repo();
        let (code, out) = run_sync(&import_args(false), dir.path());
        assert_eq!(code, 0);
        assert!(out.contains("nothing to import"));
    }

    // -- generation is idempotent and byte-stable ---------------------------

    #[test]
    fn generation_is_idempotent_and_byte_stable() {
        let (dir, _guard) = repo();
        write_canonical(dir.path(), "common.md", "Always run the full test suite.");
        write_canonical(dir.path(), "claude.md", "Prefer the native tool-use loop.");

        let (code1, _) = run_sync(&generate_args(false), dir.path());
        assert_eq!(code1, 0);
        let first_bytes = fs::read(native_claude_path(dir.path())).expect("read");

        let (code2, out2) = run_sync(&generate_args(false), dir.path());
        assert_eq!(code2, 0);
        assert!(out2.contains("unchanged"), "got {out2}");
        let second_bytes = fs::read(native_claude_path(dir.path())).expect("read");

        assert_eq!(
            first_bytes, second_bytes,
            "regenerating an already-managed, unchanged file must be byte-stable"
        );
    }

    #[test]
    fn generate_with_no_canonical_content_writes_nothing() {
        let (dir, _guard) = repo();
        let (code, out) = run_sync(&generate_args(false), dir.path());
        assert_eq!(code, 0);
        assert!(out.contains("nothing to generate"));
        assert!(!native_claude_path(dir.path()).exists());
        assert!(!native_codex_path(dir.path()).exists());
    }

    #[test]
    fn regenerating_after_a_canonical_change_updates_the_managed_file() {
        let (dir, _guard) = repo();
        write_canonical(dir.path(), "common.md", "Version one.");
        let (code, _) = run_sync(&generate_args(false), dir.path());
        assert_eq!(code, 0);

        write_canonical(dir.path(), "common.md", "Version two.");
        let (code, out) = run_sync(&generate_args(false), dir.path());
        assert_eq!(code, 0, "got {out}");
        assert!(out.contains("regenerated"));

        let content = fs::read_to_string(native_claude_path(dir.path())).expect("read");
        assert!(content.contains("Version two."));
        assert!(!content.contains("Version one."));
    }

    // -- CLI parsing ----------------------------------------------------

    #[test]
    fn sync_defaults_to_report_mode_when_no_flag_is_given() {
        let cli = ContextCli::try_parse_from(["zirv context", "sync"]).expect("parses");
        match cli.verb {
            ContextVerb::Sync(args) => {
                assert!(!args.import);
                assert!(!args.generate);
                assert!(matches!(mode(&args), SyncMode::Report));
            }
            ContextVerb::Status(_) => panic!("expected the sync verb"),
        }
    }

    #[test]
    fn sync_rejects_import_and_generate_together() {
        let result = ContextCli::try_parse_from(["zirv context", "sync", "--import", "--generate"]);
        assert!(
            result.is_err(),
            "import and generate must be mutually exclusive"
        );
    }

    #[test]
    fn help_exits_zero() {
        assert_eq!(dispatch(&["context".to_string(), "--help".to_string()]), 0);
        assert_eq!(
            dispatch(&[
                "context".to_string(),
                "sync".to_string(),
                "--help".to_string()
            ]),
            0
        );
        assert_eq!(
            dispatch(&[
                "context".to_string(),
                "status".to_string(),
                "--help".to_string()
            ]),
            0
        );
    }

    #[test]
    fn an_unknown_verb_exits_two() {
        assert_eq!(dispatch(&["context".to_string(), "nope".to_string()]), 2);
    }

    #[test]
    fn dispatch_runs_sync_report_end_to_end_in_the_current_directory() {
        let (dir, _guard) = repo();
        let _cwd = crate::commands::ctx::testenv::CwdGuard::enter(dir.path()).expect("enter repo");
        let code = dispatch(&[
            "context".to_string(),
            "sync".to_string(),
            "--report".to_string(),
        ]);
        assert_eq!(code, 0);
    }
}
